name: La publication du Storybook de DEV
permissions: {}
on:
  workflow_dispatch: # Pour activer le déclenchement manuel

jobs:
  build:
    name: "Construis"
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v4

      - name: Utiliser la version Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Installer les dépendances
        run: npm ci

      - name: Installer Playwright
        run: npx playwright install --with-deps

      - name: Exécuter les tests
        run: npm run test

      - name: Construit le Storybook de DEV
        run: npm run storybook:build-dev

      - name: Installer et configurer la CLI de S3cmd
        uses: s3-actions/s3cmd@v1.10.0
        with:
          provider: clevercloud
          access_key: ${{ secrets.CLEVER_S3_PUBLICATION_DEV_ACCESS_KEY }}
          secret_key: ${{ secrets.CLEVER_S3_PUBLICATION_DEV_SECRET_KEY }}

      - name: Nettoyer le S3
        run: s3cmd rm s3://lab-anssi-ui-kit-dev/ --recursive --force

      - name: Publier sur le S3
        run: ./scripts/s3put_avec_le_bon_mime_type.sh

      - name: Envoyer les assets vers le S3
        run: s3cmd sync --recursive -M ./src/lib/assets/* s3://lab-anssi-ui-kit-dev/src/lib/assets/
