name: L'intégration continue
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Construction de l'UI Kit du Lab. ANSSI

    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@v4

      - name: Utiliser la version Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Installer les dépendances
        run: npm ci

      - name: Contrôler le Typescript
        run: npm run check

      - name: Construire la librairie de composant
        run: npm run build

      - name: Construire le storybook
        run: npm run story:build