name: "Storybook Tests"
permissions: {}

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - ".storybook/**"
      - "outils/**"
      - "scripts/**"
      - "vite.config.ts"
      - "vite.webcomponents.config.ts"
      - "svelte.config.js"
      - "tsconfig.json"
      - "eslint.config.js"
      - ".prettierrc"
      - ".prettierignore"
      - "pnpm-lock.yaml"
      - ".github/workflows/**"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - ".storybook/**"
      - "outils/**"
      - "scripts/**"
      - "vite.config.ts"
      - "vite.webcomponents.config.ts"
      - "svelte.config.js"
      - "tsconfig.json"
      - "eslint.config.js"
      - ".prettierrc"
      - ".prettierignore"
      - "pnpm-lock.yaml"
      - ".github/workflows/**"

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt Git
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Utiliser la version Node.js 24
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 24

      - name: Installer les dépendances
        run: npm install -g "$(jq -r '.packageManager' package.json)" && pnpm install

      - name: Installer Playwright
        run: ./node_modules/.bin/playwright install chromium --with-deps

      - name: Construit le Storybook
        run: pnpm run storybook:build

      - name: Sers le Storybook et lance les tests
        run: |
          ./node_modules/.bin/concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "./node_modules/.bin/http-server storybook-static --port 6006 --silent" \
            "./node_modules/.bin/wait-on tcp:127.0.0.1:6006 && pnpm run storybook:test"
